[package]
name = "telegram-bot"
version = "1.0.0"
edition = "2021"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.4.0"
either = "1.6.1"

[dependencies.tokio]
version = "1.15.0"
features = ["full"]

[dependencies.teloxide]
version = "0.5.3"
features = ["auto-send", "macros"]